# Generated by Django 4.1.7 on 2023-03-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datafull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_author', models.TextField(blank=True, null=True)),
                ('news_title', models.TextField(blank=True, null=True)),
                ('news_content', models.TextField(blank=True, null=True)),
                ('news_counttext', models.TextField(blank=True, null=True)),
                ('news_datepublish', models.TextField(blank=True, null=True)),
                ('date_addtostored', models.TextField(blank=True, null=True)),
                ('extractive', models.TextField(blank=True, null=True)),
                ('abstractive', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='txtsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('abstractive', models.TextField(blank=True, null=True)),
                ('extractive', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
