# Generated by Django 4.1.7 on 2023-03-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_organization_organizationapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationapikey',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationAPIKey',
        ),
    ]
