# Generated by Django 4.1.7 on 2023-03-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='manager',
            field=models.CharField(max_length=150),
        ),
    ]
