# Generated by Django 4.1.7 on 2023-03-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_apikey_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='APIkey',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='manager',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
